"""empty message

Revision ID: 31e0fd9c0d05
Revises: fa41b84eab47
Create Date: 2023-04-09 10:57:26.193639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e0fd9c0d05'
down_revision = 'fa41b84eab47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lessee_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lessee_id'], ['lessees.id'], name=op.f('fk_unit_applications_lessee_id_lessees')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_unit_applications_unit_id_units')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('instructions', sa.VARCHAR(), nullable=False),
    sa.Column('minutes_to_complete', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('length(instructions) >= 50'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_recipes_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('unit_applications')
    # ### end Alembic commands ###
