"""empty message

Revision ID: 6e6b15bba09d
Revises: c43c18d8aa27
Create Date: 2023-04-04 18:41:46.505977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6b15bba09d'
down_revision = 'c43c18d8aa27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.alter_column('rent',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sec_deposit',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('beds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('baths',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sqft',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('util_incld',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('util_excld',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('lot',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('unit_num',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('zip',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.alter_column('zip',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('unit_num',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('lot',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('util_excld',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('util_incld',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('sqft',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('baths',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('beds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sec_deposit',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rent',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
