"""empty message

Revision ID: fa41b84eab47
Revises: 6e6b15bba09d
Create Date: 2023-04-05 18:49:07.287816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa41b84eab47'
down_revision = '6e6b15bba09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('unit_num', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lot', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('zip', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('beds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sqft', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('sqft')
        batch_op.drop_column('beds')
        batch_op.drop_column('zip')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('street')
        batch_op.drop_column('lot')
        batch_op.drop_column('unit_num')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
